package com.lxj.ip.domain;

import com.lixj.core.AbstractEntity;

public class Country extends AbstractEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.continent_code
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    private String continentCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.continent_name
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    private String continentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country_iso_code
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    private String countryIsoCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.country_name
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    private String countryName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.is_in_european_union
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    private Integer isInEuropeanUnion;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.continent_code
     *
     * @return the value of country.continent_code
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    public String getContinentCode() {
        return continentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.continent_code
     *
     * @param continentCode the value for country.continent_code
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    public void setContinentCode(String continentCode) {
        this.continentCode = continentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.continent_name
     *
     * @return the value of country.continent_name
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    public String getContinentName() {
        return continentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.continent_name
     *
     * @param continentName the value for country.continent_name
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    public void setContinentName(String continentName) {
        this.continentName = continentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country_iso_code
     *
     * @return the value of country.country_iso_code
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    public String getCountryIsoCode() {
        return countryIsoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country_iso_code
     *
     * @param countryIsoCode the value for country.country_iso_code
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    public void setCountryIsoCode(String countryIsoCode) {
        this.countryIsoCode = countryIsoCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.country_name
     *
     * @return the value of country.country_name
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.country_name
     *
     * @param countryName the value for country.country_name
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.is_in_european_union
     *
     * @return the value of country.is_in_european_union
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    public Integer getIsInEuropeanUnion() {
        return isInEuropeanUnion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.is_in_european_union
     *
     * @param isInEuropeanUnion the value for country.is_in_european_union
     *
     * @mbg.generated Sun May 12 20:03:41 CST 2019
     */
    public void setIsInEuropeanUnion(Integer isInEuropeanUnion) {
        this.isInEuropeanUnion = isInEuropeanUnion;
    }
}